apiVersion: v1
kind: Secret
metadata:
  name: uptime-secret
  namespace: uptime
type: Opaque
stringData:
  # для MVP ми не ставимо пароль на redis, але Secret потрібен для практики.
  REDIS_PASSWORD: ""
